@extends('layouts.public')
@section('title', 'Checkout Booking — Rentra UMKM')
@section('content')
<section class="container-app py-10">
    <div class="mb-7"><p class="section-kicker">Langkah terakhir</p><h1 class="section-title">Checkout booking</h1><p class="mt-2 text-sm text-slate-500">Periksa data pesanan sebelum dikirim ke mitra.</p></div>
    <form action="{{ route('customer.bookings.store') }}" method="POST" class="grid items-start gap-6 lg:grid-cols-[1fr_390px]">@csrf
        <input type="hidden" name="product_id" value="{{ $product->id }}"><input type="hidden" name="start_at" value="{{ $bookingData['start_at'] }}"><input type="hidden" name="end_at" value="{{ $bookingData['end_at'] }}"><input type="hidden" name="qty" value="{{ $bookingData['qty'] }}">
        <div class="space-y-6">
            <div class="card p-6"><h2 class="text-lg font-extrabold text-ink">Data customer</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><div><label class="label">Nama lengkap</label><input value="{{ auth()->user()->name }}" class="input bg-slate-50" readonly></div><div><label class="label">Nomor telepon</label><input value="{{ auth()->user()->phone }}" class="input bg-slate-50" readonly></div><div class="sm:col-span-2"><label class="label">Email</label><input value="{{ auth()->user()->email }}" class="input bg-slate-50" readonly></div><div class="sm:col-span-2"><label class="label">Catatan untuk mitra</label><textarea name="customer_notes" rows="4" class="input" placeholder="Contoh: mohon sertakan kabel tambahan...">{{ old('customer_notes') }}</textarea></div></div></div>
            <div class="card flex items-start gap-4 border-indigo-100 bg-indigo-50/60 p-5"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-indigo-600"><x-icon name="shield" /></span><div><p class="font-extrabold text-ink">Booking dilindungi Rentra</p><p class="mt-1 text-sm leading-6 text-slate-500">Mitra akan memeriksa permintaan Anda. Pembayaran baru dilakukan setelah jadwal dikonfirmasi.</p></div></div>
        </div>
        <aside class="card sticky top-24 overflow-hidden">
            <img src="{{ $product->image_url }}" class="aspect-[16/8] w-full object-cover" alt="{{ $product->name }}">
            <div class="p-6"><p class="text-xs font-bold text-indigo-600">{{ $product->partner->business_name }}</p><h2 class="mt-2 text-lg font-black text-ink">{{ $product->name }}</h2><div class="mt-5 space-y-3 border-y border-slate-100 py-5 text-sm"><div class="flex justify-between"><span class="text-slate-500">Tanggal</span><span class="font-bold text-slate-700">{{ \Carbon\Carbon::parse($bookingData['start_at'])->translatedFormat('d M Y') }} – {{ \Carbon\Carbon::parse($bookingData['end_at'])->translatedFormat('d M Y') }}</span></div><div class="flex justify-between"><span class="text-slate-500">Durasi</span><span class="font-bold">{{ $price['duration'] }} {{ $product->price_unit === 'day' ? 'hari' : 'layanan' }}</span></div><div class="flex justify-between"><span class="text-slate-500">Jumlah</span><span class="font-bold">{{ $bookingData['qty'] }} unit</span></div></div><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between text-slate-500"><span>Subtotal</span><span>Rp{{ number_format($price['subtotal'],0,',','.') }}</span></div><div class="flex justify-between text-slate-500"><span>Biaya layanan</span><span>Rp{{ number_format($price['platform_fee'],0,',','.') }}</span></div><div class="flex justify-between border-t border-slate-100 pt-4 text-lg font-black text-ink"><span>Total</span><span>Rp{{ number_format($price['total'],0,',','.') }}</span></div></div><button class="btn-primary mt-6 w-full">Buat booking →</button></div>
        </aside>
    </form>
</section>
@endsection
