@extends('layouts.dashboard')
@section('title','Dashboard Admin')
@section('page-title','Dashboard')
@section('page-subtitle','Ringkasan operasional platform RentalPro')
@section('content')
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
    <x-stat-card label="Total pengguna" :value="number_format($stats['users'])" icon="users" />
    <x-stat-card label="Mitra pending" :value="$stats['partnersPending']" icon="shield" tone="amber" hint="Perlu ditinjau" />
    <x-stat-card label="Produk menunggu" :value="$stats['productsPending']" icon="box" tone="emerald" />
    <x-stat-card label="Pembayaran ditinjau" :value="$stats['paymentsPending']" icon="card" tone="amber" />
    <x-stat-card label="Komplain terbuka" :value="$stats['complaints']" icon="alert" tone="violet" />
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]">
    <div class="space-y-6">
        <section class="card overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 class="font-extrabold text-ink">Verifikasi mitra pending</h2><p class="mt-1 text-xs text-slate-500">{{ $stats['partnersPending'] }} pengajuan menunggu</p></div><a href="{{ route('admin.partners.index',['status'=>'pending']) }}" class="text-sm font-bold text-indigo-600">Lihat semua →</a></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Mitra</th><th>Lokasi</th><th>Dokumen</th><th>Aksi</th></tr></thead><tbody>@forelse($partners as $partner)<tr><td><p class="font-bold text-ink">{{ $partner->business_name }}</p><p class="text-xs text-slate-400">{{ $partner->user->email }}</p></td><td>{{ $partner->city }}</td><td><span class="font-bold text-amber-600">{{ $partner->documents->count() }} berkas</span></td><td><a href="{{ route('admin.partners.show',$partner) }}" class="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-600">Tinjau detail</a></td></tr>@empty<tr><td colspan="4" class="py-12 text-center text-slate-400">Tidak ada mitra pending.</td></tr>@endforelse</tbody></table></div></section>
        <section class="card overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 class="font-extrabold text-ink">Moderasi produk</h2><p class="mt-1 text-xs text-slate-500">{{ $stats['productsPending'] }} produk perlu ditinjau</p></div><a href="{{ route('admin.products.index',['status'=>'pending_review']) }}" class="text-sm font-bold text-indigo-600">Lihat semua →</a></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produk</th><th>Mitra</th><th>Kategori</th><th>Aksi</th></tr></thead><tbody>@forelse($products as $product)<tr><td><div class="flex items-center gap-3"><img src="{{ $product->image_url }}" class="h-10 w-12 rounded-lg object-cover"><div><p class="max-w-[200px] truncate font-bold text-ink">{{ $product->name }}</p><p class="text-xs text-slate-400">Rp{{ number_format($product->price,0,',','.') }}</p></div></div></td><td>{{ $product->partner->business_name }}</td><td>{{ $product->category->name }}</td><td><div class="flex gap-2"><form method="POST" action="{{ route('admin.products.update',$product) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="active"><button class="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-bold text-emerald-600">Setujui</button></form><form method="POST" action="{{ route('admin.products.update',$product) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600">Tolak</button></form></div></td></tr>@empty<tr><td colspan="4" class="py-12 text-center text-slate-400">Tidak ada produk menunggu.</td></tr>@endforelse</tbody></table></div></section>
    </div>
    <aside class="space-y-6">
        <section class="card p-5"><div class="flex items-center justify-between"><h2 class="font-extrabold text-ink">Aktivitas terbaru</h2><a href="{{ route('admin.bookings.index') }}" class="text-xs font-bold text-indigo-600">Lihat semua</a></div><div class="mt-4 space-y-4">@foreach($bookings->take(5) as $booking)<div class="flex gap-3"><span class="mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><x-icon name="calendar" class="h-4 w-4" /></span><div class="min-w-0"><p class="truncate text-xs font-bold text-ink">{{ $booking->booking_code }} • {{ $booking->items->first()->product->name }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $booking->created_at->diffForHumans() }}</p></div></div>@endforeach</div></section>
        <section class="overflow-hidden rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-700 p-6 text-white shadow-xl shadow-indigo-200"><p class="text-xs font-bold text-indigo-200">Pendapatan platform</p><p class="mt-2 text-3xl font-black">Rp{{ number_format($revenue,0,',','.') }}</p><p class="mt-2 text-xs text-indigo-100/70">Akumulasi biaya layanan transaksi lunas.</p><div class="mt-6 h-24"><svg viewBox="0 0 300 80" class="h-full w-full"><path d="M0 70 C35 65 35 30 70 42 S120 70 150 35 205 18 230 35 270 50 300 10" fill="none" stroke="white" stroke-width="4" stroke-linecap="round" opacity=".9"/></svg></div></section>
    </aside>
</div>
@endsection
