@extends('layouts.dashboard')
@section('title', 'Tinjau '.$product->name)
@section('page-title', 'Detail Kamera')
@section('page-subtitle', 'Validasi data teknis, kondisi, kelengkapan, harga, dan unit fisik.')
@section('content')
<div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('admin.products.index') }}" class="text-sm font-bold text-indigo-600">← Daftar kamera</a><div class="mt-2 flex items-center gap-3"><h2 class="text-2xl font-black text-ink">{{ $product->name }}</h2><x-status-badge :status="$product->status" /></div></div><p class="text-xl font-black text-ink">Rp{{ number_format($product->price,0,',','.') }}<span class="text-xs font-medium text-slate-400">/hari</span></p></div>
<div class="grid items-start gap-6 xl:grid-cols-[1fr_370px]">
    <div class="space-y-6">
        <section class="card overflow-hidden"><img src="{{ $product->image_url }}" class="aspect-[16/7] w-full object-cover" alt=""><div class="p-6"><h3 class="font-extrabold text-ink">Deskripsi</h3><p class="mt-3 text-sm leading-7 text-slate-500">{{ $product->description }}</p></div></section>
        <section class="card p-6"><h3 class="font-extrabold text-ink">Spesifikasi teknis</h3><div class="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">@foreach([['Merek',$product->brand],['Model',$product->model],['Jenis',$product->camera_type],['Sensor',$product->sensor_type],['Resolusi',$product->resolution_mp ? $product->resolution_mp.' MP' : null],['Video',$product->video_resolution],['Mount',$product->lens_mount],['Kondisi',$product->condition_label],['Nilai penggantian','Rp'.number_format($product->replacement_value,0,',','.')]] as [$label,$value])<p><span class="block text-xs text-slate-400">{{ $label }}</span><strong class="text-ink">{{ $value ?: '-' }}</strong></p>@endforeach</div><div class="mt-6 grid gap-5 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><p class="font-bold text-ink">Kelengkapan</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-500">{{ $product->included_accessories }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="font-bold text-ink">Ketentuan</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-500">{{ $product->rental_terms }}</p></div></div></section>
        <section class="card overflow-hidden"><div class="border-b border-slate-100 p-5"><h3 class="font-extrabold text-ink">Unit fisik ({{ $product->units->count() }})</h3></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Kode</th><th>Serial</th><th>Kondisi</th><th>Ketersediaan</th></tr></thead><tbody>@foreach($product->units as $unit)<tr><td class="font-bold text-indigo-600">{{ $unit->unit_code }}</td><td>{{ $unit->serial_number ?: '-' }}</td><td>{{ str($unit->condition_status)->title() }}</td><td>{{ str($unit->availability_status)->title() }}</td></tr>@endforeach</tbody></table></div></section>
    </div>
    <aside class="space-y-6 xl:sticky xl:top-24">
        <section class="card p-6"><h3 class="font-extrabold text-ink">Mitra pemilik</h3><p class="mt-3 font-bold text-ink">{{ $product->partner->business_name }}</p><p class="mt-1 text-sm text-slate-500">{{ $product->partner->owner_name }} · {{ $product->partner->phone }}</p><p class="mt-2 text-xs leading-5 text-slate-400">{{ $product->partner->address }}, {{ $product->partner->city }}</p><a href="{{ route('admin.partners.show',$product->partner) }}" class="mt-4 inline-flex text-sm font-bold text-indigo-600">Lihat mitra →</a></section>
        <section class="card p-6"><h3 class="font-extrabold text-ink">Keputusan moderasi</h3><form action="{{ route('admin.products.update',$product) }}" method="POST" class="mt-4 space-y-3">@csrf @method('PATCH')<textarea name="admin_notes" class="input" rows="4" placeholder="Catatan atau alasan penolakan">{{ old('admin_notes',$product->admin_notes) }}</textarea><button name="status" value="active" class="btn-primary w-full">Setujui dan aktifkan</button><button name="status" value="rejected" class="btn-danger w-full">Tolak kamera</button></form></section>
    </aside>
</div>
@endsection
