@extends('layouts.dashboard')
@section('title','Booking Masuk')
@section('page-title','Booking Masuk')
@section('page-subtitle','Terima permintaan dan perbarui progres penyewaan.')
@section('content')
<form class="mb-5 flex gap-3"><select name="status" onchange="this.form.submit()" class="input max-w-xs"><option value="">Semua status</option>@foreach(['pending','waiting_payment','paid','prepared','ongoing','completed','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></form>
@if($bookings->count())<div class="space-y-4">@foreach($bookings as $booking)
<article class="card p-5"><div class="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div class="flex gap-4"><img src="{{ $booking->items->first()->product->image_url }}" class="h-20 w-24 rounded-xl object-cover"><div><div class="flex flex-wrap items-center gap-2"><p class="text-xs font-bold text-indigo-600">{{ $booking->booking_code }}</p><x-status-badge :status="$booking->status" /></div><h2 class="mt-2 font-black text-ink">{{ $booking->items->first()->product->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $booking->customer->name }} • {{ $booking->start_at->translatedFormat('d M') }}–{{ $booking->end_at->translatedFormat('d M Y') }} • {{ $booking->items->first()->qty }} unit</p></div></div><div class="flex flex-wrap items-center gap-2 lg:justify-end"><p class="mr-3 text-lg font-black text-ink">Rp{{ number_format($booking->total_amount,0,',','.') }}</p>
@if($booking->status==='pending')<form method="POST" action="{{ route('mitra.bookings.update',$booking) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="waiting_payment"><button class="btn-primary py-2">Terima</button></form><form method="POST" action="{{ route('mitra.bookings.update',$booking) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="btn-danger py-2">Tolak</button></form>
@elseif($booking->status==='paid')<form method="POST" action="{{ route('mitra.bookings.update',$booking) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="prepared"><button class="btn-primary py-2">Mulai siapkan</button></form>
@elseif($booking->status==='prepared')<form method="POST" action="{{ route('mitra.bookings.update',$booking) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="ongoing"><button class="btn-primary py-2">Mulai rental</button></form>
@elseif($booking->status==='ongoing')<form method="POST" action="{{ route('mitra.bookings.update',$booking) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="btn-primary py-2">Tandai selesai</button></form>@endif</div></div></article>
@endforeach</div><div class="mt-6">{{ $bookings->links() }}</div>@else<x-empty-state title="Belum ada booking" description="Permintaan baru dari customer akan tampil di sini." />@endif
@endsection
