@extends('layouts.dashboard')
@section('title',$product->exists?'Edit Produk':'Tambah Produk')
@section('page-title',$product->exists?'Edit Produk':'Tambah Produk')
@section('page-subtitle','Lengkapi informasi yang akan dilihat customer.')
@section('content')
<form action="{{ $product->exists ? route('mitra.products.update',$product) : route('mitra.products.store') }}" method="POST" enctype="multipart/form-data" class="grid items-start gap-6 xl:grid-cols-[1fr_320px]">@csrf @if($product->exists)@method('PUT')@endif
<div class="card p-6"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Nama produk / jasa</label><input name="name" value="{{ old('name',$product->name) }}" class="input" required></div><div><label class="label">Kategori</label><select name="category_id" class="input" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$product->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="label">Jenis produk</label><select name="product_type" class="input"><option value="rental" @selected(old('product_type',$product->product_type)==='rental')>Barang sewa</option><option value="service" @selected(old('product_type',$product->product_type)==='service')>Jasa</option><option value="sale" @selected(old('product_type',$product->product_type)==='sale')>Barang jual</option></select></div><div class="sm:col-span-2"><label class="label">Deskripsi</label><textarea name="description" rows="6" class="input" required>{{ old('description',$product->description) }}</textarea></div><div><label class="label">Harga</label><input type="number" name="price" value="{{ old('price',$product->price) }}" class="input" min="1000" required></div><div><label class="label">Satuan harga</label><select name="price_unit" class="input">@foreach(['day'=>'Per hari','hour'=>'Per jam','week'=>'Per minggu','month'=>'Per bulan','service'=>'Per layanan','item'=>'Per item'] as $value=>$label)<option value="{{ $value }}" @selected(old('price_unit',$product->price_unit)===$value)>{{ $label }}</option>@endforeach</select></div><div><label class="label">Stok / kapasitas</label><input type="number" name="stock_total" value="{{ old('stock_total',$product->stock_total ?: 1) }}" class="input" min="1" required></div><div><label class="label">Minimal durasi</label><input type="number" name="min_rent_duration" value="{{ old('min_rent_duration',$product->min_rent_duration ?: 1) }}" class="input" min="1" required></div><div><label class="label">Kota layanan</label><input name="location_city" value="{{ old('location_city',$product->location_city) }}" class="input" required></div><div><label class="label">Alamat / area</label><input name="location_address" value="{{ old('location_address',$product->location_address) }}" class="input"></div><div class="sm:col-span-2"><label class="label">Foto utama</label><input type="file" name="image" class="input" accept="image/*"><p class="mt-2 text-xs text-slate-400">JPG/PNG maksimal 3 MB. Rasio 4:3 direkomendasikan.</p></div></div></div>
<aside class="card sticky top-24 p-5"><h2 class="font-extrabold text-ink">Publikasi</h2><p class="mt-2 text-sm leading-6 text-slate-500">Simpan sebagai draf, atau ajukan agar admin meninjau produk sebelum ditampilkan.</p>@if($product->exists)<div class="mt-4 rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Status saat ini</p><div class="mt-2"><x-status-badge :status="$product->status" /></div></div>@endif<div class="mt-5 space-y-3"><button name="submit_review" value="1" class="btn-primary w-full">Ajukan untuk ditinjau</button><button name="submit_review" value="0" class="btn-secondary w-full">Simpan draf</button></div></aside>
</form>
@endsection
