@extends('layouts.dashboard')
@section('title','Profil Usaha')
@section('page-title','Profil & Dokumen')
@section('page-subtitle','Jaga data usaha tetap akurat untuk meningkatkan kepercayaan.')
@section('content')
<div class="grid items-start gap-6 xl:grid-cols-[1fr_380px]">
<form action="{{ route('mitra.profile.update') }}" method="POST" class="card p-6">@csrf @method('PATCH')<h2 class="text-lg font-extrabold text-ink">Informasi usaha</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="label">Nama usaha</label><input name="business_name" value="{{ old('business_name',$partner->business_name) }}" class="input" required></div><div><label class="label">Jenis usaha</label><input name="business_type" value="{{ old('business_type',$partner->business_type) }}" class="input"></div><div><label class="label">Nama pemilik</label><input name="owner_name" value="{{ old('owner_name',$partner->owner_name) }}" class="input" required></div><div><label class="label">Nomor telepon</label><input name="phone" value="{{ old('phone',$partner->phone) }}" class="input" required></div><div><label class="label">Kota</label><input name="city" value="{{ old('city',$partner->city) }}" class="input" required></div><div><label class="label">Provinsi</label><input name="province" value="{{ old('province',$partner->province) }}" class="input" required></div><div class="sm:col-span-2"><label class="label">Alamat</label><textarea name="address" rows="3" class="input" required>{{ old('address',$partner->address) }}</textarea></div><div class="sm:col-span-2"><label class="label">Deskripsi usaha</label><textarea name="description" rows="5" class="input">{{ old('description',$partner->description) }}</textarea></div></div><button class="btn-primary mt-6">Simpan profil</button></form>
<div class="space-y-6"><section class="card p-5"><div class="flex items-center justify-between"><h2 class="font-extrabold text-ink">Verifikasi mitra</h2><x-status-badge :status="$partner->verification_status" /></div><p class="mt-3 text-sm leading-6 text-slate-500">Unggah dokumen yang sah. Admin akan meninjau dan memberi catatan jika diperlukan.</p><form action="{{ route('mitra.documents.store') }}" method="POST" enctype="multipart/form-data" class="mt-5 space-y-3">@csrf<select name="document_type" class="input"><option value="ktp">KTP Pemilik</option><option value="nib">NIB</option><option value="sku">SKU</option><option value="npwp">NPWP</option><option value="rekening">Rekening Bank</option><option value="foto_usaha">Foto Usaha</option></select><input name="document_number" class="input" placeholder="Nomor dokumen (opsional)"><input type="file" name="file" class="input" required><button class="btn-primary w-full">Upload dokumen</button></form></section><section class="card p-5"><h2 class="font-extrabold text-ink">Dokumen terkirim</h2><div class="mt-4 space-y-3">@forelse($partner->documents as $document)<div class="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p class="text-sm font-bold uppercase text-ink">{{ $document->document_type }}</p><p class="text-xs text-slate-400">{{ $document->created_at->translatedFormat('d M Y') }}</p></div><x-status-badge :status="$document->status" /></div>@empty<p class="text-sm text-slate-400">Belum ada dokumen.</p>@endforelse</div></section></div>
</div>
@endsection
